# Spring properties

# Configure this Discovery Server  
spring:
  application:
    name: service-discovery

# HTTP Server
server:
  port: 9001   # HTTP (Tomcat) port
  
eureka:
  instance:
    hostname: 192.168.4.240
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 30000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://192.168.4.240:9001/eureka/
      
  

  