spring:
# HikariConfig
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://192.168.4.195:3306/sms_service?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    #username: test
    #password: 111
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 300
    minimumIdle: 10
    autoCommit: true;
    connectionTestQuery: SELECT 1

#redis
config:
  jedis :  
    jedisShardInfo :  
      host : 192.168.4.236
      port : 6379  
      password : meiduiredis2016  
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true

# mybatis-config
mybatis: 
  mapper-locations: classpath:com/meidui/sms/mapper/*Mapper.xml