spring:
# HikariConfig
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.45.178.235:3306/sms_service?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username: sms_service
    password: sms_service@meidui.?!
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    maximumPoolSize: 300
    minimumIdle: 10
    autoCommit: true;
    connectionTestQuery: SELECT 1

#redis
  redis: 
    database: 15
    #host: 192.168.4.236
    host: 10.45.178.235
    port: 6379
    password: meiduiredis2017Md?! 
    timeout: 60
    pool: 
      max-active: 1024
      max-wait: 2000
      max-idle: 250
      min-idle: 8
      testOnBorrow: true
      testOnReturn: true

# mybatis-config
mybatis: 
  mapper-locations: classpath:com/meidui/shortmsg/mapper/*Mapper.xml