---
spring:
  profiles: dev
# HikariConfig
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.4.236:3306/meidui_settlement?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: meidui@2016.?!
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 300
      minimumIdle : 10
      pool-name: harika-cp
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.240:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true  
  instance:
    #hostname: 192.168.4.240
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress:localhost}:${server.port}/swagger-ui.html
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）    
      
## it doesn't work configuring here so change to configure it in MyBatisConfig.java.  
#mybatis:
#  mapper-locations: classpath*:com/meiduimall/settlement/mapper/*Mapper.xml
#  type-aliases-package: com.meiduimall.settlement.model

# redis
config:
  jedis: 
    jedisShardInfo:  
      host: 192.168.4.236  
      port: 6379  
      password: meiduiredis2016 
      database: 1
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis: 2000 
    testOnBorrow: true
    testOnReturn: true
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #缺省为1000

#自定义的属性和值  
myProps :
  oauthSignatureMethod : MD5
  oauthVersion : 1.0
  oauthAccessorSecret : 25164dbe226e1d26c109b64c7e6d1
  oauthConsumerKey : 7aee283f0dd2a877d8cb2f7464b345345
  #http://vipt.meiduimall.com/
  url : http://192.168.4.241:8080/
  belong : Authorized/querySecondLevelShareMem
  apiUpdFirstReferrerCash : AuthorizationAccount/accountBalanceChanges
  ##callback url from o2o
  o2oUrl : http://192.168.4.241/
  o2oSaveOrderBillStatu : op/index.php/java/saveOrderBillStatus
  o2oAddProxyFee : op/index.php/java/addProxyFee
  o2oGetStoreInfo : op/index.php/java/getActiveStoreInfo
  o2oApiKey : mdo2okey
  ##msg channel
  ##url from sms
  smsUrl : http://192.168.4.240:20000/
  smsSendMessage : notify/short_msg_service/v1/new/send_common_sms_message
  ##phones:xuyanxiong,guidonglin
  smsPhones : 13410336992,13798431927
  ##new member
  memUrl : http://192.168.4.240:8098/
  memAccountUrl : http://192.168.4.240:8096/
  memCheckUseridExists : member/member_service/v1/check_userid_exists
  memAccountAdjustAmount : member/account_service/v1/account_adjust_amount

---
spring:
  profiles: prepro
# HikariConfig
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.170.135.70:3306/meidui_settlement?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: meidui
    password: meiduishop
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 300
      minimumIdle : 10
      pool-name: harika-cp
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.45.178.235:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true  
  instance:
    #hostname: 10.45.178.235
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress:localhost}:${server.port}/swagger-ui.html
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

## it doesn't work configuring here so change to configure it in MyBatisConfig.java.  
#mybatis:
#  mapper-locations: classpath*:com/meiduimall/settlement/mapper/*Mapper.xml
#  type-aliases-package: com.meiduimall.settlement.model

# redis
config:
  jedis: 
    jedisShardInfo:  
      host: 10.170.135.70
      port: 6379  
      password: meiduiredis2017
      database: 1
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis: 2000 
    testOnBorrow: true
    testOnReturn: true
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #缺省为1000
            
#自定义的属性和值  
myProps :
  oauthSignatureMethod : MD5
  oauthVersion : 1.0
  oauthAccessorSecret : 25164dbe226e1d26c109b64c7e6d14e8
  oauthConsumerKey : 7aee283f0dd2a877d8cb2f7464b3a9da
  #http://vipt.meiduimall.com/
  url : http://10.170.13.129:18123/
  belong : Authorized/querySecondLevelShareMem
  apiUpdFirstReferrerCash : AuthorizationAccount/accountBalanceChanges
  ##callback url from o2o
  o2oUrl : http://10.24.167.124/
  o2oSaveOrderBillStatu : op/index.php/java/saveOrderBillStatus
  o2oAddProxyFee : op/index.php/java/addProxyFee
  o2oApiKey : mdo2okey
  ##msg channel
  ##url from sms
  smsUrl : http://10.45.178.235:20000/
  smsSendMessage : notify/short_msg_service/v1/new/send_common_sms_message
  ##phones:xuyanxiong,guidonglin
  smsPhones : 13410336992,13798431927,18898447755

---
spring:
  profiles: pro
# HikariConfig
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meidui_settlement?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 300
      minimumIdle : 10
      pool-name: harika-cp
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.116.21.93:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true  
  instance:
    #hostname: 10.116.21.93
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress:localhost}:${server.port}/swagger-ui.html
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

## it doesn't work configuring here so change to configure it in MyBatisConfig.java.  
#mybatis:
#  mapper-locations: classpath*:com/meiduimall/settlement/mapper/*Mapper.xml
#  type-aliases-package: com.meiduimall.settlement.model

# redis
config:
  jedis: 
    jedisShardInfo:  
      host: 127.0.0.1
      port: 6379  
      password: 123456
      database: 1
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis: 2000 
    testOnBorrow: true
    testOnReturn: true
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #缺省为1000
            
#自定义的属性和值  
myProps :
  oauthSignatureMethod : MD5
  oauthVersion : 1.0
  oauthAccessorSecret : 25164dbe226e1d26c109b64c7e6d14e8
  oauthConsumerKey : 7aee283f0dd2a877d8cb2f7464b3a9da
  #http://vipt.meiduimall.com/
  url : http://10.170.13.129:18123/
  belong : Authorized/querySecondLevelShareMem
  apiUpdFirstReferrerCash : AuthorizationAccount/accountBalanceChanges
  ##callback url from o2o
  o2oUrl : http://10.24.167.124/
  o2oSaveOrderBillStatu : op/index.php/java/saveOrderBillStatus
  o2oAddProxyFee : op/index.php/java/addProxyFee
  o2oApiKey : mdo2okey
  ##msg channel
  ##url from sms
  smsUrl : http://10.116.21.93:20000/
  smsSendMessage : notify/short_msg_service/v1/new/send_common_sms_message
  ##phones:xuyanxiong,guidonglin
  smsPhones : 13410336992,13798431927,18898447755

---
spring:
  profiles: test
  # HikariConfig
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.110:3306/meidui_settlement?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: meidui
    password: meiduishop
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 300
      minimumIdle : 10
      pool-name: harika-cp
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.111:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true  
  instance:
    #hostname: 10.45.178.235
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    status-page-url: http://${spring.cloud.client.ipAddress:localhost}:${server.port}/swagger-ui.html
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）    

## it doesn't work configuring here so change to configure it in MyBatisConfig.java.  
#mybatis:
#  mapper-locations: classpath*:com/meiduimall/settlement/mapper/*Mapper.xml
#  type-aliases-package: com.meiduimall.settlement.model

# redis
config:
  jedis: 
    jedisShardInfo:  
      host : 192.168.4.110
      port : 6379  
      password : meiduiredis2017
      database: 1
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis: 2000 
    testOnBorrow: true
    testOnReturn: true
hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #缺省为1000
            
#自定义的属性和值  
myProps :
  oauthSignatureMethod : MD5
  oauthVersion : 1.0
  oauthAccessorSecret : 25164dbe226e1d26c109b64c7e6d1
  oauthConsumerKey : 7aee283f0dd2a877d8cb2f7464b345345
  #http://vipt.meiduimall.com/
  url : http://vipt.meiduimall.com/
  belong : Authorized/querySecondLevelShareMem
  apiUpdFirstReferrerCash : AuthorizationAccount/accountBalanceChanges
  ##callback url from o2o
  o2oUrl : http://o2ot.meiduimall.com/
  o2oSaveOrderBillStatu : op/index.php/java/saveOrderBillStatus
  o2oAddProxyFee : op/index.php/java/addProxyFee
  o2oApiKey : mdo2okey
  ##msg channel
  ##url from sms
  smsUrl : http://10.45.178.235:20000/
  smsSendMessage : notify/short_msg_service/v1/new/send_common_sms_message
  ##phones:xuyanxiong,guidonglin
  smsPhones : 13410336992,13798431927