
---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.240:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true  
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）    
config:
  jedis :  
    jedisShardInfo :  
      host : 192.168.4.236
      port : 6379  
      password : meiduiredis2016  
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true

---
spring:
  profiles: prepro
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.45.178.235:9001/eureka/
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）
config:
  jedis :
    jedisShardInfo :
      host : 10.170.135.70
      port : 6379
      password : meiduiredis2017
    maxTotal: 1024
    maxIdle: 250
    maxWaitMillis : 2000
    testOnBorrow: true
    testOnReturn: true

---
spring:
  profiles: pro
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.116.21.93:9001/eureka/
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）
config:
  jedis :
    jedisShardInfo :
      host : 127.0.0.1
      port : 6379
      password : 123456
    maxTotal: 1024
    maxIdle: 250
    maxWaitMillis : 2000
    testOnBorrow: true
    testOnReturn: true

---
spring:
  profiles: test
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.111:9001/eureka/
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
  instance:
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）
config:
  jedis :
    jedisShardInfo :
      host : 192.168.4.110
      port : 6379
      password : meiduiredis2017
    maxTotal: 1024
    maxIdle: 250
    maxWaitMillis : 2000
    testOnBorrow: true
    testOnReturn: true
