#端口
server:
  port: 10023

# AOP
spring :
  aop :
    auto : true
    proxy-target-class : true

datasource1:
  type : com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.4.236:3306/meiduishop0302?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
  username: root
  password: meidui@2016.?!
  hikari:
    connection-init-sql: SELECT 1
    connection-test-query: SELECT 1 FROM DUAL
    auto-commit: true
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 300
    minimumIdle : 10
    pool-name: harika-cp
    
datasource2:
  type : com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.4.236:3306/meiduishop0302?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
  username: root
  password: meidui@2016.?!
  hikari:
    connection-init-sql: SELECT 1
    connection-test-query: SELECT 1 FROM DUAL
    auto-commit: true
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 300
    minimumIdle : 10
    pool-name: harika-cp2    
           
search_server_url: http://127.0.0.1:8088/solr    
