datasource1:
  type : com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://127.0.0.1:3306/sqldb?useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123
  hikari:
    connection-init-sql: SELECT 1
    connection-test-query: SELECT 1 FROM DUAL
    auto-commit: true
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 300
    minimumIdle : 10
    pool-name: harika-cp
    
datasource2:
  type : com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.4.195:3306/sqldb?useUnicode=true&characterEncoding=utf-8
  username: test
  password: 111
  hikari:
    connection-init-sql: SELECT 1
    connection-test-query: SELECT 1 FROM DUAL
    auto-commit: true
    connection-timeout: 30000
    idle-timeout: 600000
    max-lifetime: 1800000
    maximum-pool-size: 300
    minimumIdle : 10
    pool-name: harika-cp2    
           
search_server_url: http://127.0.0.1:8081/solr    
API_KEY_NAME: ^%\#$\#$fdlkjf908564fdafdafsdaf&^%&%\#$@
first_xfc_price_url: http://192.168.4.181:80/Authorized/GetXFCPrice
first_xfc_rate: 85
first_xfc_secret: 25164dbe226e1d26c109b64c7e6d14e8
first_xfc_key:  7aee283f0dd2a877d8cb2f7464b3a9da  