# server port
server :
  port : 20110
  
# AOP
spring :  
  aop :
    auto : true
    proxy-target-class : true
  application:
    name: md1gw-access 

---
spring :
  profiles : dev
# HikariConfig  
  datasource:
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.236:3306/meiduishop?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : root
    password : meidui@2016.?!
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true;
    connectionTestQuery : SELECT 1

#自定义的属性和值  
myProps :
  routeServiceUrl : http://192.168.4.240:9050    #网关路由
  userCenterUrl : http://192.168.4.240:8097      #会员中心接入层
  sendSmsUrl : http://192.168.4.240:20000        #发送短信
  payUrl : http://payd.meiduimall.com            #支付接入开发环境
  meiduimallUrl : http://shopdev.meiduimall.com  #商城开发环境
  finishUrl : http://shopdev.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: Test123
  otoUrl : http://t3.o2o.meiduimall.com

---
spring :
  profiles : prepro
# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://10.170.135.70:3306/sqldb?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : meidui
    password : meiduishop
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true;
    connectionTestQuery : SELECT 1

#自定义的属性和值  
myProps :
  routeServiceUrl : http://10.45.178.235:9050 #网关路由
  userCenterUrl : http://vipy.api.meiduimall.com   #会员中心接入层
  sendSmsUrl : http://10.45.178.235:20000     #发送短信
  payUrl : http://payy.meiduimall.com          #支付接入生产环境
  meiduimallUrl : http://shopy.meiduimall.com          #商城预发布环境
  finishUrl : http://shopy.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: 20822875
  otoUrl : http://o2oy.meiduimall.com

---
spring :
  profiles : pro
# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://127.0.0.1:3306/sqldb?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : meidui
    password : meiduishop
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true;
    connectionTestQuery : SELECT 1

#自定义的属性和值  
myProps :
  routeServiceUrl : http://10.116.21.93:9050  #网关路由
  userCenterUrl : http://vip.api.meiduimall.com   #会员中心接入层
  sendSmsUrl : http://10.116.21.93:20000     #发送短信
  payUrl : http://pay.meiduimall.com          #支付接入生产环境
  meiduimallUrl : http://www.meiduimall.com          #商城生产环境
  finishUrl : http://www.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: 20822875
  otoUrl : http://shangjia.meiduimall.com

---
spring :
  profiles : test
# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.110:3306/sqldb?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : meidui
    password : meiduishop
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true
    connectionTestQuery : SELECT 1

#自定义的属性和值  
myProps :
  routeServiceUrl : http://192.168.4.111:9050    #网关路由
  userCenterUrl : http://vipt.api.meiduimall.com      #会员中心接入层
  sendSmsUrl : http://192.168.4.111:20000        #发送短信
  payUrl : http://payt.meiduimall.com            #支付计入测试环境
  meiduimallUrl : http://md.meiduimall.com  #商城测试环境
  finishUrl : http://md.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: Test123
  otoUrl : http://o2ot.meiduimall.com
