# server port
server :
  port : 20110
  
# AOP
spring :
  aop :
    auto : true
    proxy-target-class : true
  application:
    name: md1gw-access  
  profiles :
     active : test 

# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.178:3306/meiduishop?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : root
    password : 123456
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true;
    connectionTestQuery : SELECT 1
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.240:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true   
  instance:
    hostname: 192.168.4.240
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   


hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #熔断时间为3000





# redis
config :
  jedis :  
    jedisShardInfo :  
      host : 192.168.4.236
      port : 6379  
      password: meiduiredis2016 
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true
    
    
#自定义的属性和值  
myProps :
  routeServiceUrl : http://192.168.4.240:9050
  userCenterUrl : http://192.168.4.240:8097
  sendSmsUrl : http://192.168.4.240:20000
  paydUrl : http://payd.meiduimall.com
  payUrl : http://pay.meiduimall.com