# server port
server :
  port : 20110
  
# AOP
spring :  
  aop :
    auto : true
    proxy-target-class : true
  application:
    name: md1gw-access 


---
spring :
  profiles : dev
# HikariConfig  
  datasource:
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.236:3306/meiduishop?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : meidui
    password : meiduishop
    hikari:
      connection-init-sql: SELECT 1
      connection-test-query: SELECT 1 FROM DUAL
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 300
      minimumIdle : 10
      pool-name: harika-cp    
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.240:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true   
  instance:
    hostname: 192.168.4.240
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #熔断时间为3000

# redis
config :
  jedis :  
    jedisShardInfo :  
      host : 192.168.4.236
      port : 6379  
      password: meiduiredis2016 
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true

#自定义的属性和值  
myProps :
  routeServiceUrl : http://192.168.4.240:9050    #网关路由
  userCenterUrl : http://192.168.4.240:8097      #会员中心接入层
  sendSmsUrl : http://192.168.4.240:20000        #发送短信
  payUrl : http://payd.meiduimall.com            #支付接入开发环境
  meiduimallUrl : http://shopdev.meiduimall.com  #商城开发环境
  finishUrl : http://www.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: Test123

---
spring :
  profiles : prepro
# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.178:3306/meiduishop?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : meidui
    password : meiduishop
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true;
    connectionTestQuery : SELECT 1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.45.178.235:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true   
  instance:
    hostname: 10.45.178.235
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #熔断时间为3000

# redis
config :
  jedis :  
    jedisShardInfo :  
      host : 192.168.4.236
      port : 6379  
      password: meiduiredis2016 
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true
    
#自定义的属性和值  
myProps :
  routeServiceUrl : http://10.45.178.235:9050 #网关路由
  userCenterUrl : http://vip.api.meiduimall.com   #会员中心接入层
  sendSmsUrl : http://10.45.178.235:20000     #发送短信
  payUrl : http://pay.meiduimall.com          #支付接入生产环境
  meiduimallUrl : www.meiduimall.com          #商城生产环境
  finishUrl : http://www.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: 20822875

---
spring :
  profiles : pro
# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.178:3306/meiduishop?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : meidui
    password : meiduishop
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true;
    connectionTestQuery : SELECT 1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.116.21.93:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true   
  instance:
    hostname: 10.116.21.93
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #熔断时间为3000

# redis
config :
  jedis :  
    jedisShardInfo :  
      host : 10.116.21.93
      port : 6379  
      password: meiduiredis2016 
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true
    
#自定义的属性和值  
myProps :
  routeServiceUrl : http://10.116.21.93:9050  #网关路由
  userCenterUrl : http://vip.api.meiduimall.com   #会员中心接入层
  sendSmsUrl : http://10.116.21.93:20000     #发送短信
  payUrl : http://pay.meiduimall.com          #支付接入生产环境
  meiduimallUrl : www.meiduimall.com          #商城生产环境
  finishUrl : http://www.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: 20822875


---
spring :
  profiles : test
# HikariConfig
  datasource :
    type : com.zaxxer.hikari.HikariDataSource
    driver-class-name : com.mysql.jdbc.Driver
    url : jdbc:mysql://192.168.4.110:3306/sqldb?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    username : root
    password : 123456
    connectionTimeout : 30000
    idleTimeout : 600000
    maxLifetime : 1800000
    maximumPoolSize : 300
    minimumIdle : 10
    autoCommit : true
    connectionTestQuery : SELECT 1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.4.111:9001/eureka/
    registry-fetch-interval-seconds: 10  
    healthcheck:
      enabled: true   
  instance:
    hostname: 192.168.4.111
    lease-renewal-interval-in-seconds: 15      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 30  # 发呆时间，即服务续约到期时间（缺省为90s）   

hystrix:  
  command:  
    default:  
      execution:  
        isolation:  
          thread:  
            timeoutInMilliseconds: 3000 #熔断时间为3000

# redis
config:
  jedis:
    jedisShardInfo:
      host: 192.168.4.110
      port: 6379
      password: meiduiredis2017
    maxTotal: 1024
    maxIdle: 250
    maxWaitMillis: 2000
    testOnBorrow: true
    testOnReturn: true

#自定义的属性和值  
myProps :
  routeServiceUrl : http://192.168.4.111:9050    #网关路由
  userCenterUrl : http://vipt.api.meiduimall.com      #会员中心接入层
  sendSmsUrl : http://192.168.4.111:20000        #发送短信
  payUrl : http://payt.meiduimall.com            #支付计入测试环境
  meiduimallUrl : http://md.meiduimall.com  #商城测试环境
  finishUrl : http://www.meiduimall.com/wap/finish.html #完成url
  signClientID : mall_java
  signKey: Test123

