server:
  port: 8097
  
# AOP
spring :
  aop :
    auto : true
    proxy-target-class : true
    
# redis
config :
  jedis :  
    jedisShardInfo :  
      host : 192.168.4.236  
      port : 6379  
      password: meiduiredis2016 
    maxTotal: 1024  
    maxIdle: 250  
    maxWaitMillis : 2000 
    testOnBorrow: true
    testOnReturn: true