server:
  port: 10092
   
# AOP
spring :
  aop :
    auto : true
    proxy-target-class : true

# 配置微服务网关
service : 
  host : http://192.168.4.240:9050
  sign-clientID : mall_java
  sign-key : Test123
    