server:
  port: ${PORT:10092}

---
spring:
  profiles: dev

# 配置clientID和key
sign : 
  clientID : mall_java
  key : Test123 

# 商品模块微服务地址
catalog-service : 
  host : http://192.168.4.240:9050
# 会员系统接入层地址
member-access : 
  host : http://192.168.4.240:8097

---
spring:
  profiles: prepro

# 配置clientID和key
sign : 
  clientID : mall_java
  key : 20822875

# 商品模块微服务地址
catalog-service : 
  host : http://10.45.178.235:9050
# 会员系统接入层地址
member-access : 
  host : http://vip.api.meiduimall.com

---
spring:
  profiles: pro
 
# 配置clientID和key
sign : 
  clientID : mall_java
  key : 20822875

# 商品模块微服务地址
catalog-service : 
  host : http://10.116.21.93:9050
# 会员系统接入层地址
member-access : 
  host : http://vip.api.meiduimall.com

---
spring:
  profiles: test

# 配置clientID和key
sign : 
  clientID : mall_java
  key : Test123 

# 商品模块微服务地址
catalog-service : 
  host : http://192.168.4.111:9050
# 会员系统接入层地址
member-access : 
  host : http://vipt.api.meiduimall.com
